name: ramayana
description: "A Game based on Ramayana."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.66+66

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  bonfire: ^3.3.0
  flame_audio: ^2.1.7
  video_player: ^2.8.2
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.3
  logger: ^2.0.2+1
  animated_text_kit: ^4.2.2
  flame: 1.14.0

dev_dependencies:
  flame_lint:
  flutter_launcher_icons:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/splash/
    - assets/images/
    - assets/images/maps/
    - assets/worlds/
    - assets/
    - assets/images/platform/
    - assets/images/platform/hanuman/
    - assets/images/platform/rakshasa/
    - assets/translations/
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "../graphics/icon_ios.png"
  image_path_ios: "../graphics/icon_ios.png"
  adaptive_icon_background: "../graphics/background.png"
  adaptive_icon_foreground: "../graphics/foreground.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "../graphics/icon_ios.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "../graphics/icon_ios.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "../graphics/icon_ios.png"
